*
* !! DO NOT EDIT THIS FILE !!
*
* This file was automatically generated with the
* copy_equate program, and so should not be edited.
*
* This source was created on Thu Jan 27 11:41:52 2011*
* This source created from original file jimi.h.
*
EQUATE JBASE_SQM_VARIABLES TO 1     ;* List of all variables in the source 
EQUATE JBASE_SQM_SUBROUTINES TO 2     ;* All subroutines called 
EQUATE JBASE_SQM_COMMON_READ TO 3     ;* COMMON variables read only 
EQUATE JBASE_SQM_PATHLENGTH TO 4     ;* Length of internal subroutines 
EQUATE JBASE_SQM_INSERT TO 5     ;* INSERT statements 
EQUATE JBASE_SQM_UNREACHABLE TO 6     ;* Code that cannot be reached 
EQUATE JBASE_SQM_PERFORM TO 7     ;* PERFORM/EXECUTE statements 
EQUATE JBASE_SQM_STAY_LINES TO 8     ;* Multiple commands on same line 
EQUATE JBASE_SQM_COMMENTS TO 9     ;* Ratio of comments to code 
EQUATE JBASE_SQM_SUBROUTINE_COMMENTS TO 10     ;* Comments that follow a label 
EQUATE JBASE_SQM_SELECT TO 11     ;* All SELECT statements 
EQUATE JBASE_SQM_RELEASE TO 12     ;* All RELEASE statements 
EQUATE JBASE_SQM_RELEASE_VAR TO 13     ;* All 'RELEASE VAR' statements 
EQUATE JBASE_SQM_TRANSACTION TO 14     ;* Transaction statements 
EQUATE JBASE_SQM_GOTO TO 15     ;* GOTO statements (firing offence) 
EQUATE JBASE_SQM_RETURNTO TO 16     ;* All 'RETURN TO' statements 
EQUATE JBASE_SQM_NEST_DEPTH TO 17     ;* Nested depths that exceed 2 
EQUATE JBASE_SQM_NEST_LENGTH TO 18     ;* If more than 30 code lines in a nest 
EQUATE JBASE_SQM_DATE TO 50     ;* Date in internal format 
EQUATE JBASE_SQM_TIME TO 51     ;* Time in internal format 
EQUATE JBASE_SQM_JBASE_USER TO 52     ;* JBASE user name 
EQUATE JBASE_SQM_OS_USER TO 53     ;* Operating system user name 
EQUATE JBASE_JIMI_TRACEFLAGS_CALL TO 1   ;* 0x00000001 Trace all CALL statements 
EQUATE JBASE_JIMI_TRACEFLAGS_PERFORM TO 2   ;* 0x00000002 Trace all PERFORM/EXECUTE statements 
EQUATE JBASE_JIMI_TRACEFLAGS_OPEN TO 4   ;* 0x00000004 Trace all OPEN statements 
EQUATE JBASE_JIMI_TRACEFLAGS_FILEIO TO 8   ;* 0x00000008 Trace all remaining file I/O operations 
EQUATE JBASE_JIMI_TRACEFLAGS_TRANSACTION TO 16   ;* 0x00000010 Trace all transaction operations 
EQUATE JBASE_JIMI_TRACEFLAGS_GENERAL TO 32   ;* 0x00000020 General JIMI operations turned on 
EQUATE JBASE_JIMI_TRACEFLAGS_VERBOSE TO 64   ;* 0x00000040 Some options want verbose output 
EQUATE JBASE_JIMI_TRACEFLAGS_SUBVAR TO 128   ;* 0x00000080 Trace list of Subroutine variables 
EQUATE JBASE_JIMI_TRACEFLAGS_HOLDIO TO 512   ;* 0x00000200 Hold FILEIO before and after images in memory 
EQUATE JBASE_JIMI_TRACEFLAGS_COMMITIO TO 1024   ;* 0x00000400 Trace IO occuring during commit in progress  
EQUATE JBASE_JIMI_SUBVAR_ENTRY TO 1   ;* Trace taken at Sub entry 
EQUATE JBASE_JIMI_SUBVAR_EXIT TO 2   ;* Trace taken at Sub exit 
EQUATE JBASE_JIMI_SUBVAR_JIMION TO 3   ;* Trace taken at JIMI ON 
EQUATE JBASE_JIMI_SUBVAR_JIMIOFF TO 4   ;* Trace taken at JIMI OFF 
EQUATE JBASE_JIMI_ORIGIN_BASIC TO 0   ;* Trace on initiated from BASIC 
EQUATE JBASE_JIMI_ORIGIN_JDIAG TO 1   ;* Trace on initiated from JDIAG 
EQUATE JBASE_JIMI_ACTION_SUBINIT TO 1     ;* A subroutine has been called 
EQUATE JBASE_JIMI_ACTION_SUBEND TO 2     ;* A RETURN from a subroutine 
EQUATE JBASE_JIMI_ACTION_OPEN TO 3     ;* A OPEN statement was executed 
EQUATE JBASE_JIMI_ACTION_OPENSEQ TO 4     ;* A OPENSEQ statement was executed 
EQUATE JBASE_JIMI_ACTION_TRANSTART TO 5     ;* A TRANSTART statement was executed 
EQUATE JBASE_JIMI_ACTION_TRANSEND TO 6     ;* A TRANSEND statement was executed 
EQUATE JBASE_JIMI_ACTION_TRANSABORT TO 7     ;* A TRANSABORT statement was executed 
EQUATE JBASE_JIMI_ACTION_READ TO 8     ;* A READ statement was executed 
EQUATE JBASE_JIMI_ACTION_WRITE TO 9     ;* A WRITE statement was executed 
EQUATE JBASE_JIMI_ACTION_DELETE TO 10     ;* A DELETE statement was executed 
EQUATE JBASE_JIMI_ACTION_CLEARFILE TO 11     ;* A CLEARFILE statement was executed 
EQUATE JBASE_JIMI_ACTION_RELEASE TO 12     ;* A RELEASE statement was executed 
EQUATE JBASE_JIMI_ACTION_SELECT TO 13     ;* A SELECT statement was executed 
EQUATE JBASE_JIMI_ACTION_SELECTEND TO 14     ;* A SELECT statement was completed 
EQUATE JBASE_JIMI_ACTION_PERFORM TO 15     ;* A PERFORM or EXECUTE statement was executed 
EQUATE JBASE_JIMI_ACTION_JIMION TO 100     ;* JIMI turned ON 
EQUATE JBASE_JIMI_ACTION_JIMIOFF TO 101     ;* JIMI turned OFF 
DEFC  JIMITraceOn(INT , VAR , VAR )
DEFC  JIMITraceOff(INT)
DEFC VAR JIMIBeforeImage()
DEFC VAR JIMIAfterImage()
