/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.2.0.GA (WildFly Core 6.0.11.Final-redhat-00001) - 2.0.15.Final-redhat-00001
 * Generated at: 2025-10-08 06:37:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class genrequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-Control","no-cache,no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader ("Expires", 0);

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String routArgs=request.getParameter("routineArgs"); 
      out.write('\r');
      out.write('\n');
 String routName=request.getParameter("routineName"); 
      out.write('\r');
      out.write('\n');
 String compId=request.getParameter("compId"); 
      out.write('\r');
      out.write('\n');
 String usrRole=request.getParameter("usrRole"); 
      out.write('\r');
      out.write('\n');
 String skin=request.getParameter("skin"); 
      out.write('\r');
      out.write('\n');
 String server=request.getServerName(); 
      out.write('\r');
      out.write('\n');
 int portno=request.getServerPort(); 
      out.write('\r');
      out.write('\n');
 String compScreen=request.getParameter("compScreen"); 
      out.write('\r');
      out.write('\n');
 String contextRoot=request.getContextPath(); 
      out.write('\r');
      out.write('\n');
 String windowName=request.getParameter("windowName"); 
      out.write('\r');
      out.write('\n');
 String user=request.getParameter("user"); 
      out.write('\r');
      out.write('\n');
 String WS_replaceAll=request.getParameter("WS_replaceAll"); 
      out.write('\r');
      out.write('\n');
 String WS_parentComposite=request.getParameter("WS_parentComposite"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("      <link rel=\"icon\" href=\"../plaf/icon/favicon.ico\"/>\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"../plaf/style/");
      out.print( skin );
      out.write("/general.css\">\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\t<script src=\"../scripts/jsp.js\"></script>\r\n");
      out.write("\t<title>Processing...</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("      <body onLoad=\"dorequest()\" oncontextmenu=\"return false;\">\r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"33%\"></td>\r\n");
      out.write("\t\t\t\t<td align=\"middle\" width=\"34%\" height=\"75\"><P align=\"center\"></P>\r\n");
      out.write("\t\t\t\t\t<P align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<img border=\"0\" src=\"../plaf/images/default/gears.gif\">\r\n");
      out.write("\t\t\t\t\t</P>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"33%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form name=\"request\" method=\"POST\" action=\"../servlet/BrowserServlet\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"requestType\" value=\"UTILITY.ROUTINE\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"routineName\" value=\"");
      out.print( routName );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"routineArgs\" value=\"");
      out.print( routArgs );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"command\" value=\"globusCommand\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"companyId\" value=\"");
      out.print( compId );
      out.write("\"/>\t\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"userRole\" value=\"");
      out.print( usrRole );
      out.write("\"/>    \r\n");
      out.write("            <input type=\"hidden\" name=\"compScreen\" value=\"");
      out.print( compScreen );
      out.write("\"/>\t\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"windowName\" value=\"");
      out.print( windowName );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"user\" value=\"");
      out.print( user );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"WS_replaceAll\" value=\"");
      out.print( WS_replaceAll );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"WS_parentComposite\" value=\"");
      out.print( WS_parentComposite );
      out.write("\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
